---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hocs-converter
  labels:
    version: {{.VERSION}}
spec:
  replicas: {{.REPLICAS}}
  selector:
    matchLabels:
      name: hocs-converter
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: hocs-converter
        role: hocs-backend
        version: {{.VERSION}}
    spec:
      containers:
      - name: certs
        image: quay.io/ukhomeofficedigital/cfssl-sidekick-jks:v0.0.6
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        args:
          - --certs=/certs
          - --domain=hocs-converter.${KUBE_NAMESPACE}.svc.cluster.local
          - --expiry=8760h
          - --command=/usr/local/scripts/trigger_nginx_reload.sh
        env:
          - name: KUBE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - name: certs
            mountPath: /certs
          - name: bundle
            mountPath: /etc/ssl/certs
            readOnly: true
      - name: proxy
        image: quay.io/ukhomeofficedigital/nginx-proxy:v3.2.9
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        resources:
         limits:
          memory: "100Mi"
          cpu: 100m
         requests:
          memory: "50Mi"
          cpu: 100m
        env:
          - name: PROXY_SERVICE_HOST
            value: '127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '8081'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
          - name: HTTPS_REDIRECT
            value: 'FALSE'
          - name: SERVER_CERT
            value: /certs/tls.pem
          - name: SERVER_KEY
            value: /certs/tls-key.pem
          - name: ADD_NGINX_SERVER_CFG
            value: 'gzip off; location = /reload { allow 127.0.0.1; deny all; content_by_lua_block { os.execute("touch /tmp/nginx-reload-triggered; /usr/local/openresty/nginx/sbin/nginx -s reload; touch /tmp/nginx-reload-complete;") } }'
        volumeMounts:
          - name: certs
            mountPath: /certs
            readOnly: true
        ports:
          - name: https
            containerPort: 10443
      - name: hocs-converter
        image: quay.io/ukhomeofficedigital/hocs-converter:{{.VERSION}}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        env:
          - name: PORT
            value: '8080'
          - name: MAX_FILESIZE
            valueFrom:
              configMapKeyRef:
                name: hocs-converter
                key: max_filesize
          - name: SUPPORTED_TYPES
            valueFrom:
              configMapKeyRef:
                name: hocs-converter
                key: supported_types
          - name: CONVERTER_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: hocs-converter
                key: converter_timeout
          - name: NODE_ENV
            value: 'production'
        resources:
          limits:
            cpu: 1000m
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 100Mi
        ports:
          - name: http
            containerPort: 8080
        volumeMounts:
          - mountPath: /tmp
            name: docs
            readOnly: false
      volumes:
        - name: certs
          emptyDir:
            medium: "Memory"
        - name: docs
          emptyDir:
            medium: "Memory"
        - name: bundle
          configMap:
            name: bundle
